# Site settings
title: PHP Developers Nepal
#email: avinash@avinash.com.np
description: > # this means to ignore newlines until "baseurl:"
  Wiki and Knowledgebase for the PHP Developers Community, Nepal
baseurl: "/php/" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#github_username:  phpDevelopersNepal

# Build settings
markdown: kramdown

# add a new custom collection for meetups
collections:
  meetup:
    output: true
